### ISSUE TITLE
flappie: Failed find read name under /Raw/Reads/

### ISSUE THREAD

**Issue by thuelsm** [nanoporetech/flappie#32]
Hello,

Hi,

when trying to basecall Fast5 files I get the following error:

`flappie: Failed find read name under /Raw/Reads/`
`flappie: No basecall returned for ...`

The data come directly from the MinION. I checked the files and they seem correct.
Using the HDFView tool, I checked that the reads have names.

Does anyone have an idea how to fix this error?

Greetings

**Comment by thuelsm** [comment]
To test if the error is due to my data I have also tested the latest version of scrappie. Scrappie gave me the same error message.

On the GitHub page of scrappie, there is someone else who has the same problem:
[scrappie/issues/31](https://github.com/nanoporetech/scrappie/issues/31
)

I have used the latest MinKNOW software.

**Comment by tmassingham-ont** [comment]
Hello.  This is likely due to trying to use 'multi-read' fast5 with `flappie`.  

Presently, both `flappie` and `scrappie` only support the older single-read fast5 format.  The work-around is convert the reads using the `multi_to_single_fast5` tool from the `ont-fast5-api` package (see  https://github.com/nanoporetech/flappie/issues/25).

Sorry for the inconvenience.

**Comment by thuelsm** [comment]
Hello @tmassingham-ont, many thanks for your help.

After the conversion to fast5 single files flappie is now working.
